# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pmod_color_constraint.xdc

# Block Designs: bd/pmod_color_ip_block/pmod_color_ip_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block || ORIG_REF_NAME==pmod_color_ip_block} -quiet] -quiet

# IP: bd/pmod_color_ip_block/ip/pmod_color_ip_block_processing_system7_0_0/pmod_color_ip_block_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block_processing_system7_0_0 || ORIG_REF_NAME==pmod_color_ip_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/pmod_color_ip_block/ip/pmod_color_ip_block_PmodCOLOR_0_0/pmod_color_ip_block_PmodCOLOR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block_PmodCOLOR_0_0 || ORIG_REF_NAME==pmod_color_ip_block_PmodCOLOR_0_0} -quiet] -quiet

# IP: bd/pmod_color_ip_block/ip/pmod_color_ip_block_xbar_0/pmod_color_ip_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block_xbar_0 || ORIG_REF_NAME==pmod_color_ip_block_xbar_0} -quiet] -quiet

# IP: bd/pmod_color_ip_block/ip/pmod_color_ip_block_auto_pc_0/pmod_color_ip_block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block_auto_pc_0 || ORIG_REF_NAME==pmod_color_ip_block_auto_pc_0} -quiet] -quiet

# IP: bd/pmod_color_ip_block/ip/pmod_color_ip_block_ps7_0_axi_periph_0/pmod_color_ip_block_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==pmod_color_ip_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pmod_color_ip_block/ip/pmod_color_ip_block_rst_ps7_0_50M_0/pmod_color_ip_block_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_color_ip_block_rst_ps7_0_50M_0 || ORIG_REF_NAME==pmod_color_ip_block_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/abe447/workspace/ece520/final_project/hardware/project_1/project_1.gen/sources_1/bd/pmod_color_ip_block/pmod_color_ip_block_ooc.xdc
